dev:
  adapter: postgres
  database: iot-camera
  username: tosashimanto
  password: 123456
  host: localhost     #defaults to 127.0.0.1
  port: 5432
  sslmode: disable
  idle_conns: 10
  open_conns: 100

#dev:
#  adapter: mysql
#  database: iot-camera
#  username: root
#  password:
#  host: localhost     #defaults to 127.0.0.1
#  port: 3306
#  idle_conns: 10
#  open_conns: 100
#  redis:
#    address: localhost:6379
#    password:
#  mongodb:
#    database: restful_api_sample_dev
#    path: localhost
#    max_pool: 20


staging:
  adapter: mysql
  database: restful_api_sample_stag
  username: root
  password:
  host: localhost     #defaults to 127.0.0.1
  port: 3306
  idle_conns: 10
  open_conns: 100

prod:
  adapter: postgres
  database: restful_api_sample_prod
  username: postgres
  password: postgres
  host: localhost     #defaults to 127.0.0.1
  port: 5432
  sslmode: disable
  idle_conns: 10
  open_conns: 100

